# Generated by Django 5.1.3 on 2024-11-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='cruise',
            name='destinations',
            field=models.ManyToManyField(related_name='destinations', to='app.destination'),
        ),
    ]
