# Generated by Django 5.1.3 on 2024-11-23 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cruise_destination_delete_myuser_cruise_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
