# Generated by Django 5.1.3 on 2024-11-23 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cruise_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='destination',
        ),
        migrations.AddField(
            model_name='cruise',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
