# Generated by Django 5.1.3 on 2024-11-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cruise_destination_cruise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='description',
            field=models.TextField(default='Enter description...', max_length=2000),
        ),
    ]
